### ISSUE TITLE
Cast LongType to CHAR_STRING instead of INTEGER

### ISSUE THREAD

**Issue by SaschaVetter** [werneckpaiva/spark-to-tableau#2]
Tableau extracts have no support for the data type long. I'd recommend to cast it to CHAR_STRING/VARCHAR instead of INTEGER. 

I can't find a recommendation from Tableau to do so, except this partly [unrelated discussion](https://community.tableau.com/message/466343#466343).

**Comment by SaschaVetter** [comment]
@werneckpaiva What is your thought on this?

**Comment by werneckpaiva** [comment]
It's sad that Tableau doesn't support long. Both solutions are not good. We can go with char. At least we will not loose any data truncating to integer.

**Comment by SaschaVetter** [comment]
Just for the record. My first statement was incorrect, there is a support for the data type long. It just took me a bit to figure out how to use it.
